function(link_targets_by_pattern OUT_TARGET)
  cmake_parse_arguments(PARSE "" "" "PATTERNS;EXCLUDE" ${ARGN})
  if(NOT TARGET ${OUT_TARGET})
    add_library(${OUT_TARGET} INTERFACE)
  endif()

  # Collect all targets in the project
  set(ALL_DIRS ".")
  set(ALL_TARGETS "")
  set(INDEX 0)
  while(TRUE)
      list(LENGTH ALL_DIRS DIR_COUNT)
      if(NOT INDEX LESS DIR_COUNT)
          break()
      endif()

      list(GET ALL_DIRS ${INDEX} CURRENT_DIR)
      get_property(DIR_TARGETS DIRECTORY "${CURRENT_DIR}" PROPERTY BUILDSYSTEM_TARGETS)
      list(APPEND ALL_TARGETS ${DIR_TARGETS})
      get_property(SUB_DIRS DIRECTORY "${CURRENT_DIR}" PROPERTY SUBDIRECTORIES)
      list(APPEND ALL_DIRS ${SUB_DIRS})
      math(EXPR INDEX "${INDEX} + 1")
    endwhile()

    # Filter targets by patterns and exclusions
    foreach(TGT IN LISTS ALL_TARGETS)
      if("${TGT}" STREQUAL "${INTERFACE_LIB}")
          continue()
      endif()

      # Skip excluded targets
      list(FIND PARSE_EXCLUDE ${TGT} _EXCL)
      if(NOT _EXCL EQUAL -1)
        continue()
      endif()

      # Check Inclusion Patterns (Auto-wrapping with ^ and .*)
      foreach(PATTERN IN LISTS PARSE_PATTERNS)
          if(TGT MATCHES "^${PATTERN}.*")
              get_target_property(TGT_TYPE ${TGT} TYPE)
              if(NOT TGT_TYPE STREQUAL "EXECUTABLE")
                  message(STATUS "[${OUT_TARGET}] Auto-linked: ${TGT}")
                  target_link_libraries(${OUT_TARGET} INTERFACE ${TGT})
                  break() 
              endif()
          endif()
      endforeach()
    endforeach()
endfunction()
